### ISSUE TITLE
some functions which should haven't needed privileges require privileges due to path()

### ISSUE THREAD

**Issue by sprhawk** [cezarmathe/btrfsutil-rs#1]
Some functions in libbtrfsutil, like `btrfs_subvolume_create_snapshot`, do not require privilege (CAP_SYS_ADMIN),
But inside `Subvolume::snapshot`, it calls `Subvolume::path`, which requires privilege, that cause these functions require privilege too.

**Comment by cezarmathe** [comment]
Hi!
I was thinking about storing the path of the subvolume inside the `Subvolume` struct, too. I think that would solve this issue.

**Comment by sprhawk** [comment]
> Hi!
> I was thinking about storing the path of the subvolume inside the `Subvolume` struct, too. I think that would solve this issue.

Yeah, sure, it will do. And I think it needs to transform relative path into absolute path too if you save that path.

**Comment by cezarmathe** [comment]
Waiting to see what happens to this: https://github.com/kdave/btrfs-progs/issues/252

**Comment by cezarmathe** [comment]
Fixed by #14

**Comment by sprhawk** [comment]
Cool
