### ISSUE TITLE
Subvolume::path() only works on btrfs root filesystem

### ISSUE THREAD

**Issue by agrover** [cezarmathe/btrfsutil-rs#3]
Calling `btrfs_util_subvolume_path` with path "/" only works if btrfs is the filesystem mounted at /. If I have a btrfs filesystem mounted at `/mnt/btrfs` (and some other filesystem type is mounted at `/`), the filesystem root that needs to be passed is `/mnt/btrfs`.

I think this means a `Subvolume` needs to have some way to remember its filesystem root.

**Comment by cezarmathe** [comment]
Yes, that is right. Thanks for pointing out!

**Comment by cezarmathe** [comment]
Fixed by #4
