### ISSUE TITLE
Do a release?

### ISSUE THREAD

**Issue by joshhansen** [cezarmathe/btrfsutil-rs#35]
btrfsutil-rs 0.2.0?

I'm currently relying on `master` but this prevents me from publishing to crates.io. I published to `btrfsutil-fake` to work around this, but would prefer to use the mainline.

**Comment by NAlexPear** [comment]
Absolutely. I need to rework the build + test pipeline and handle the dependency on an [out-of-date `loopdev`](https://github.com/mdaffin/loopdev/issues/68) (PR #36), then I'll get this release out there. Thanks for the push to do so :+1:

**Comment by NAlexPear** [comment]
@joshhansen [`v0.2.0`](https://crates.io/crates/btrfsutil/0.2.0) has been released.

**Comment by joshhansen** [comment]
Awesome, thank you!
